# HW01

In [1]:
import numpy as np

## 1.a

Решение

$$
\begin{bmatrix} 
7 & 1 & -1 \\ 
1 & -3 & 5 \\ 
-6 & 2 & -2 
\end{bmatrix}
\begin{bmatrix} 
-9 & -6 & 2 \\ 
0 & -5 & 5 \\ 
0 & 5 & -7 
\end{bmatrix}
=
$$

$$
=
\begin{bmatrix} 
7*(-9)+1*0+(-1)*0 & 7*(-6)+1*(-5)+(-1)*5 & 7*2+1*5+(-1)*(-7) \\ 
1*(-9)+(-3)*0+5*0 & 1*(-6)+(-3)*(-5)+5*5 & 1*2+(-3)*5+5*(-7)  \\ 
-6*(-9)+2*0+(-2)*0 & -6*(-6)+2*(-5)+(-2)*5 & -6*2+2*5+(-2)*(-7) 
\end{bmatrix}
=
$$

$$
=
\begin{bmatrix} 
-63+0+0 & -42-5-5 & 14+5+7 \\ 
-9+0+0 & -6+15+25 & 2-15-35 \\ 
54+0+0 & 36-10-10 & -12+10+14
\end{bmatrix}
=
\begin{bmatrix} 
-63 & -52 & 26 \\ 
-9 & 34 & -48 \\ 
54 & 16 & 12
\end{bmatrix}
$$

Проверка

In [2]:
A = np.array([
    [7,1,-1],
    [1,-3,5],
    [-6,2,-2]
])

B = np.array([
    [-9,-6,2],
    [0,-5,5],
    [0,5,-7]
])

In [3]:
np.matmul(A, B)

array([[-63, -52,  26],
       [ -9,  34, -48],
       [ 54,  16,  12]])

## 1.b

Решение

$$
\begin{bmatrix} 
-9 & 5 & 2 \\ 
-8 & -3 & 4 \\ 
-5 & 8 & -8 
\end{bmatrix}
\begin{bmatrix} 
1 & -5 & 1 \\ 
7 & 3 & 1 \\ 
-2 & 4 & 7 
\end{bmatrix}
=
$$

$$
=
\begin{bmatrix} 
-9 \\ 
-8 \\ 
-5 
\end{bmatrix}
\begin{bmatrix} 
1 & -5 & 1 \\ 
\end{bmatrix}
+
\begin{bmatrix} 
5 \\ 
-3 \\ 
8
\end{bmatrix}
\begin{bmatrix} 
7 & 3 & 1 \\ 
\end{bmatrix}
+
\begin{bmatrix} 
2 \\ 
4 \\ 
-8 
\end{bmatrix}
\begin{bmatrix}
-2 & 4 & 7 
\end{bmatrix}
=
$$

$$
=
\begin{bmatrix} 
-9 & 45 & -9 \\ 
-8 & 40 & -8 \\ 
-5 & 25 & -5 
\end{bmatrix}
+
\begin{bmatrix} 
35 & 15 & 5 \\ 
-21 & -9 & -3 \\ 
56 & 24 & 8 
\end{bmatrix}
+
\begin{bmatrix} 
-4 & 8 & 14  \\ 
-8 & 16 & 28  \\ 
16 & -32 & -56 
\end{bmatrix}
=
\begin{bmatrix} 
22 & 68 & 10  \\ 
-37 & 47 & 17  \\ 
67 & 17 & -53 
\end{bmatrix}
$$

Проверка

In [4]:
A = np.array([
    [-9,5,2],
    [-8,-3,4],
    [-5,8,-8]
])

B = np.array([
    [1,-5,1],
    [7,3,1],
    [-2,4,7]
])

In [5]:
np.matmul(A, B)

array([[ 22,  68,  10],
       [-37,  47,  17],
       [ 67,  17, -53]])

## 2.a

$$
\begin{vmatrix} 
4 & 1 \\ 
-7 & -8
\end{vmatrix}
=
4*(-8)-1*(-7)= -25
$$

In [6]:
A = np.array([
    [4,1],
    [-7,-8],
])

In [7]:
round(np.linalg.det(A))

-25.0

## 2.b

$$
\begin{vmatrix} 
7 & 2 & -9 \\
9 & -2 & 4 \\
0 & 2 & -1
\end{vmatrix}
=
0*
\begin{vmatrix} 
2 & -9 \\ 
-2 & 4
\end{vmatrix}
-2*
\begin{vmatrix} 
7 & -9 \\ 
9 & 4
\end{vmatrix}
+(-1)*
\begin{vmatrix} 
7 & 2 \\ 
9 & -2
\end{vmatrix}
=
-2*(28-(-81))-(-14-18)=-186
$$

In [8]:
A = np.array([
    [7,2,-9],
    [9,-2,4],
    [0,2,-1]
])

In [9]:
round(np.linalg.det(A))

-186.0

## 2.c

$$
\begin{vmatrix} 
1 & -7 & -3 \\
4 & 4 & -1 \\
1 & 0 & 0
\end{vmatrix}
=
1*
\begin{vmatrix} 
-7 & -3 \\ 
4 & -1
\end{vmatrix}
-0*
\begin{vmatrix} 
1 & -3 \\ 
4 & -1
\end{vmatrix}
+0*
\begin{vmatrix} 
1 & -7 \\ 
4 & 4
\end{vmatrix}
=
7-(-12)=19
$$

In [10]:
A = np.array([
    [1,-7,-3],
    [4,4,-1],
    [1,0,0]
])

In [11]:
round(np.linalg.det(A))

19.0

## 2.d

Дано

$$
A=
\begin{bmatrix} 
5 & 5 & 5 & 0 \\
1 & 4 & 0 & 1 \\
-2 & -6 & 0 & 1 \\
0 & -6 & 3 & -2
\end{bmatrix}
$$

Разложим по столбцу 3:

$$
det(A)=
5*
\begin{vmatrix} 
1 & 4 & 1 \\
-2 & -6 & 1 \\
0 & -6 & -2
\end{vmatrix}
-3*
\begin{vmatrix} 
5 & 5 & 0 \\
1 & 4 & 1 \\
-2 & -6 & 1
\end{vmatrix}
=
$$

$$
=
5*(-(-6)*
\begin{vmatrix} 
1 & 1 \\ 
-2 & 1
\end{vmatrix}
-2*
\begin{vmatrix} 
1 & 4 \\ 
-2 & -6
\end{vmatrix}
)-3*(5*
\begin{vmatrix} 
4 & 1 \\ 
-6 & 1
\end{vmatrix}
-5*
\begin{vmatrix} 
1 & 1 \\ 
-2 & 1
\end{vmatrix}
)
=
$$

$$
= 5*[6*(1-(2))-2*(-6-(-8))]-3*[5*(4-(-6))-5*(1-(-2))] = 5*(18-4)-3*(50-15)=5*14-3*35=-35
$$

In [12]:
A = np.array([
    [5,5,5,0],
    [1,4,0,1],
    [-2,-6,0,1],
    [0,-6,3,-2],
])

In [13]:
round(np.linalg.det(A))

-35.0

## 3.a

Дана матрица:
$$
A=
\begin{bmatrix} 
3 & -2 \\ 
-5 & -1
\end{bmatrix}
$$

Решение:

$$
det(A-\lambda E)=
\begin{vmatrix} 
3-\lambda & -2 \\ 
-5 & -1-\lambda
\end{vmatrix}
=0
$$

$$
(3-\lambda)(-1-\lambda)-(-5)(-2) = -(3\lambda-\lambda^2-\lambda+3)-10=\lambda^2-2\lambda-13=0
$$

Найдем корни:

In [14]:
np.roots([1, -2, -13])

array([ 4.74165739, -2.74165739])

$$
\lambda_1 = 4.74 \\
\lambda_2 = -2.74
$$

Проверка

In [15]:
A = np.array([
    [3,-2],
    [-5,-1],
])

In [16]:
_, V = np.linalg.eig(A)
D = np.diag([4.74, -2.74])
V_inv = np.linalg.inv(V)

In [17]:
np.linalg.multi_dot([V, D, V_inv])

array([[ 2.99911409, -1.99911409],
       [-4.99778522, -0.99911409]])

## 3.b

Дана матрица:

$$
A=
\begin{bmatrix} 
6 & -3 & -2 \\ 
0 & -6 & -2 \\ 
-3 & 3 & -1 
\end{bmatrix}
$$

Решение:

$$
det(A-\lambda E)=
\begin{vmatrix} 
6-\lambda & -3 & -2 \\ 
0 & -6-\lambda & -2 \\ 
-3 & 3 & -1-\lambda 
\end{vmatrix}
=0
$$

$$
(-6-\lambda)
\begin{vmatrix} 
6-\lambda & -2 \\ 
-3 & -1-\lambda 
\end{vmatrix}
-(-2)
\begin{vmatrix} 
6-\lambda & -3 \\ 
-3 & 3 \\ 
\end{vmatrix}
=0
$$

$$
(-6-\lambda)[(6-\lambda)(-1-\lambda)-(-3)(-2)]+2[3(6-\lambda)-(-3)(-3)]=0
$$

$$
(-6-\lambda)(-6+\lambda-6\lambda+\lambda^2-6)+2(18-3\lambda-9) = 0
$$

$$
(-6-\lambda)(\lambda^2-5\lambda-12)-6\lambda+18=0
$$

$$
-6\lambda^2-\lambda^3+30\lambda+5\lambda^2+72+12\lambda-6\lambda+18=0
$$

$$
\lambda^3+\lambda^2-36\lambda-90=0
$$

Найдем корни:

In [18]:
np.roots([1, 1, -36, -90])

array([ 6.56776436, -4.56776436, -3.        ])

$$
\lambda_1 = 6.57 \\
\lambda_2 = -4.57 \\
\lambda_3 = -3
$$

Проверка

In [19]:
A = np.array([
    [6,-3,-2],
    [0,-6,-2],
    [-3,3,-1]
])

In [20]:
eigenvalues, _ = np.linalg.eig(A)

In [21]:
eigenvalues

array([ 6.56776436, -3.        , -4.56776436])

## 4.a

$$
\lim_{x\to\infty} 
\frac{4x^2+3x}{5x^2+17x-7}
=
\lim_{x\to\infty} 
\frac{4+\frac{3}x}{5+\frac{17}x-\frac{7}{x^2}}
=\frac{4}5
$$

## 4.b

$$
\lim_{x\to\infty} 
\frac{100x^2+17x-3}{x^3+x^2+x+1}
=
\lim_{x\to\infty} 
\frac{\frac{100}{x}+\frac{17}{x^2}-\frac{3}{x^3}}{1+\frac{1}{x}+\frac{1}{x^2}+\frac{1}{x^3}}
=0
$$

## 4.c

$$
\lim_{x\to\infty} 
\frac{x^2+4x+11+\sin(x)}{3x^2+x-2}
=
\lim_{x\to\infty} 
\frac{1+\frac{4}{x}+\frac{11}{x^2}+\frac{\sin(x)}{x^2}}{3+\frac{1}{x}-\frac{2}{x^2}}
=\frac{1}3
$$

## 4.d

$$
\lim_{x\to\infty} 
\frac{7x^2-2x-4+\cos(x)}{7x^2-7x+7+\sin(x)}
=
\lim_{x\to\infty} 
\frac{7-\frac{2}{x}-\frac{4}{x^2}+\frac{\cos(x)}{x^2}}{7-\frac{7}{x}+\frac{7}{x^2}+\frac{\sin(x)}{x^2}}
=\frac{7}7=1
$$

## 4.e

$$
\lim_{x\to\infty}
\left(1+\frac{1}{2x}\right)^{3x}
=
\lim_{x\to\infty}
\left[
\left(1+\frac{1}{2x}\right)^{2x}
\right]^{\frac{3}{2}}
=e^{\frac{3}{2}}
$$

## 4.f

$$
\lim_{x\to\infty}
\left(
\frac{x-1}{x+1}
\right)^{x+2}
=
\lim_{x\to\infty}
\left(
\frac{x+1-2}{x+1}
\right)^{x+1+1}
=
\lim_{x\to\infty}
\left(
\frac{x+1-2}{x+1}
\right)^{x+1}
\cdot
\lim_{x\to\infty}
\left(
\frac{x+1-2}{x+1}
\right)=
$$

$$
=
\lim_{x\to\infty}
\left(
1+
\frac{-2}{x+1}
\right)^{x+1}
\cdot
1=
\lim_{x\to\infty}
\left(
1+
\frac{-2}{x+1}
\right)^{\frac{x+1}{-2}(-2)}
=
\lim_{x\to\infty}
\left[
\left(
1+\frac{-2}{x+1}
\right)^{\frac{x+1}{-2}}
\right]^{-2}
=e^{-2}
$$

## 4.g

$$
\lim_{x\to 0}
\frac{\arctan(x)-\sin(x)}{x^5}
=
\lim_{x\to 0}
\frac{x-\frac{x^3}{3}+O(x^5)-(x-\frac{x^3}{3!}+O(x^5))}{x^5}
=
$$

$$
=
\lim_{x\to 0}
\frac{x-\frac{x^3}{3}+O(x^5)-x+\frac{x^3}{6}+O(x^5))}{x^5}
=
\lim_{x\to 0}
\frac{-\frac{x^3}{6}+O(x^5)}{x^5}
=
\lim_{x\to 0}
\frac{-1}{6x^2}+O(1)
=-\infty
$$

## 5.a

Преобразовать при $x\to 0$:

$$
(1+x^4+x^5+O(x^9))(1+x^3+x^4+O(x^9))=
$$

$$
=
1+x^4+x^5+O(x^9)+x^3+x^7+x^8+x^3O(x^9)+x^4+x^8+x^9+x^4O(x^9)+O(x^9)+x^4O(x^9)+x^5O(x^9)+O(x^9)O(x^9)
=
$$

$$
=
1+x^3+2x^4+x^5+x^7+2x^8+x^9+O(x^9)+O(x^{12})+O(x^{13})+O(x^{14})+O(x^{18})
=
$$

$$
=
1+x^3+2x^4+x^5+x^7+2x^8+x^9+O(x^9))=1+x^3+2x^4+x^5+x^7+2x^8+O(x^9))
$$

## 6.a, 6.b

Дана случайная величина X:

|Значение|Верятность|
|:------:|----------|
|-2|0.1|
|-1|0.1|
|0|0.3|
|1|0.2|
|2|0.05|
|3|0.25|

Решение

In [22]:
E_X = -2*0.1+(-1)*0.1+0*0.3+1*0.2+2*0.05+3*0.25

In [23]:
var_x = 0.1*(-2-E_X)**2+0.1*(-1-E_X)**2+0.3*(0-E_X)**2+0.2*(1-E_X)**2+0.05*(2-E_X)**2+0.25*(3-E_X)**2

In [24]:
print('Математическое ожидание:', round(E_X, 2))
print('Дисперсия:', round(var_x, 2))

Математическое ожидание: 0.75
Дисперсия: 2.59


Проверка

In [25]:
values = [-2, -1, 0, 1, 2, 3]
probs = [0.1, 0.1, 0.3, 0.2, 0.05, 0.25]

In [26]:
N = 1000000

print('E[X]:', np.random.choice(values, N, p=probs).mean())
print('var(X):', np.random.choice(values, N, p=probs).var())

E[X]: 0.748176
var(X): 2.5870832672640005


## 6.c

Дана случайная величина:

$$
X \sim U(1,4)
$$

In [27]:
E_X = (1+4)*0.5

In [28]:
var_x = (4-1)**2 / 12

In [29]:
print('Математическое ожидание:', round(E_X, 2))
print('Дисперсия:', round(var_x, 2))

Математическое ожидание: 2.5
Дисперсия: 0.75


Проверка

In [30]:
N = 1000000

print('E[X]:', np.random.uniform(1, 4, N).mean())
print('var(X):', np.random.uniform(1, 4, N).var())

E[X]: 2.5006199103041094
var(X): 0.7500354025047793


## 6.d

Дана случайная величина:

$$
X \sim U(-5,7)
$$

In [31]:
E_X = (-5+7)*0.5

In [32]:
var_x = (7-(-5))**2 / 12

In [33]:
print('Математическое ожидание:', round(E_X, 2))
print('Дисперсия:', round(var_x, 2))

Математическое ожидание: 1.0
Дисперсия: 12.0


Проверка

In [34]:
N = 1000000

print('E[X]:', np.random.uniform(-5, 7, N).mean())
print('var(X):', np.random.uniform(-5, 7, N).var())

E[X]: 0.9989229997320624
var(X): 12.007320763310947
