# Сингулярное разложение $A = U\Sigma V^T$

In [14]:
import numpy as np
from scipy.linalg import svd, inv, eigh

np.set_printoptions(precision=2, suppress=True)

In [15]:
A = [3, 7, 5, 2]
B = [0, 1, 3, 2, 3, 1, 0, 1, 0]
C = [5, 7, 6, 4, 2, 1, 3, 4, 1, 3, 3, 4, 5, 4, 1]

In [16]:
A, B, C = np.array(A), np.array(B), np.array(C)

In [17]:
A = A.reshape(2, 2)

In [18]:
B.shape

(9,)

In [19]:
B = B.reshape(3, 3)

In [20]:
C.shape

(15,)

In [21]:
C = C.reshape(5, -1)

## Разложение матрицы A

In [22]:
A

array([[3, 7],
       [5, 2]])

In [23]:
r = np.linalg.matrix_rank(A)
r

2

Домножим на $A^T$ слева:
$
A^TA=(U\Sigma V^T)^TU\Sigma V^T=
V\Sigma^TU^TU\Sigma V^T=
V\Sigma^T\Sigma V^T=
V\Sigma^2V^T
$, где  
- $V$ - собственные векторы $A^TA$,  
- $\Sigma^2$ - собственные значения $A^TA$

In [24]:
evals, evecs = eigh(A.T @ A)

In [25]:
evals

array([11.08, 75.92])

In [26]:
evecs

array([[-0.8 ,  0.59],
       [ 0.59,  0.8 ]])

In [27]:
desc_ind = np.argsort(evals)[::-1]
evals = evals[desc_ind]
evecs = evecs[:, desc_ind]

In [28]:
S = np.diag(np.sqrt(evals))
V = evecs

Домножим $A = U\Sigma V^T$ на $V\Sigma^{-1}$ справа: $U = AV\Sigma^{-1}$

In [29]:
S_inv = np.diag(np.reciprocal(np.diagonal(S)))
np.allclose(S_inv, inv(S), atol=1e-02)

True

In [30]:
U = A @ V @ S_inv

In [31]:
U, S, V.T

(array([[ 0.85,  0.53],
        [ 0.53, -0.85]]),
 array([[8.71, 0.  ],
        [0.  , 3.33]]),
 array([[ 0.59,  0.8 ],
        [-0.8 ,  0.59]]))

Проверим:

In [32]:
np.allclose(U @ S @ V.T, A, atol=1e-02)

True

In [33]:
svd(A)

(array([[-0.85, -0.53],
        [-0.53,  0.85]]),
 array([8.71, 3.33]),
 array([[-0.59, -0.8 ],
        [ 0.8 , -0.59]]))

## Разложение матрицы B

In [34]:
B

array([[0, 1, 3],
       [2, 3, 1],
       [0, 1, 0]])

In [35]:
r = np.linalg.matrix_rank(B)
r

3

In [36]:
U, s, Vt = svd(B)

In [37]:
U, s, Vt

(array([[-0.57,  0.82,  0.04],
        [-0.81, -0.54, -0.23],
        [-0.17, -0.17,  0.97]]),
 array([4.34, 2.42, 0.57]),
 array([[-0.37, -0.73, -0.58],
        [-0.45, -0.4 ,  0.8 ],
        [-0.81,  0.56, -0.18]]))

In [38]:
np.allclose(U @ np.diag(s) @ Vt, B, atol=1e-02)

True

## Разложение матрицы C

In [39]:
C

array([[5, 7, 6],
       [4, 2, 1],
       [3, 4, 1],
       [3, 3, 4],
       [5, 4, 1]])

In [40]:
r = np.linalg.matrix_rank(C)
r

3

Домножим на $C^T$ слева:
$
C^TC=(U\Sigma V^T)^TU\Sigma V^T=
V\Sigma^TU^TU\Sigma V^T=
V\Sigma^T\Sigma V^T=
V\Sigma^2V^T
$, где  
- $V$ - собственные векторы $C^TC$,  
- $\Sigma^2$ - собственные числа $C^TC$

In [41]:
CTC = C.T @ C
evals_v, evecs_v = eigh(CTC)

In [42]:
evals_v

array([  2.94,  13.59, 216.47])

In [43]:
evecs_v

array([[ 0.53, -0.6 , -0.6 ],
       [-0.76, -0.02, -0.65],
       [ 0.38,  0.8 , -0.46]])

In [44]:
desc_ind = np.argsort(evals_v)[::-1]
evals_v = evals_v[desc_ind]
evecs_v = evecs_v[:, desc_ind]

In [45]:
evals_v

array([216.47,  13.59,   2.94])

In [46]:
evecs_v

array([[-0.6 , -0.6 ,  0.53],
       [-0.65, -0.02, -0.76],
       [-0.46,  0.8 ,  0.38]])

In [47]:
S = np.diag(np.sqrt(evals_v))
V = evecs_v * -1

In [48]:
S

array([[14.71,  0.  ,  0.  ],
       [ 0.  ,  3.69,  0.  ],
       [ 0.  ,  0.  ,  1.71]])

In [49]:
V

array([[ 0.6 ,  0.6 , -0.53],
       [ 0.65,  0.02,  0.76],
       [ 0.46, -0.8 , -0.38]])

Домножим на $C^T$ справа:
$
CC^T=U\Sigma V^T(U\Sigma V^T)^T=
U\Sigma V^TV\Sigma^TU^T=
U\Sigma\Sigma^T U^T=
U\Sigma^2U^T
$, где  
- $U$ - собственные векторы $CC^T$,  
- $\Sigma^2$ - собственные значения $CC^T$

In [50]:
CCT = C @ C.T
evals_u, evecs_u = eigh(CCT)

In [51]:
evals_u

array([ -0.  ,  -0.  ,   2.94,  13.59, 216.47])

In [52]:
evecs_u

array([[ 0.  ,  0.49,  0.21, -0.47,  0.7 ],
       [-0.57,  0.26, -0.58,  0.44,  0.28],
       [-0.46, -0.47,  0.61,  0.29,  0.33],
       [ 0.09, -0.68, -0.49, -0.37,  0.38],
       [ 0.68, -0.01, -0.01,  0.61,  0.41]])

In [53]:
desc_ind = np.argsort(evals_u)[::-1]
evals_u = evals_u[desc_ind]
evecs_u = evecs_u[:, desc_ind]

In [54]:
evals_u = evals_u[:r]
evecs_u = evecs_u[:, :r]

In [55]:
evecs_u

array([[ 0.7 , -0.47,  0.21],
       [ 0.28,  0.44, -0.58],
       [ 0.33,  0.29,  0.61],
       [ 0.38, -0.37, -0.49],
       [ 0.41,  0.61, -0.01]])

In [56]:
np.allclose(S, np.diag(np.sqrt(evals_u)), atol=1e-02)

True

In [57]:
U = evecs_u

In [58]:
U, S, V.T

(array([[ 0.7 , -0.47,  0.21],
        [ 0.28,  0.44, -0.58],
        [ 0.33,  0.29,  0.61],
        [ 0.38, -0.37, -0.49],
        [ 0.41,  0.61, -0.01]]),
 array([[14.71,  0.  ,  0.  ],
        [ 0.  ,  3.69,  0.  ],
        [ 0.  ,  0.  ,  1.71]]),
 array([[ 0.6 ,  0.65,  0.46],
        [ 0.6 ,  0.02, -0.8 ],
        [-0.53,  0.76, -0.38]]))

Проверим:

In [59]:
np.allclose(U @ S @ V.T, C, atol=1e-02)

True

In [60]:
svd(C, full_matrices=False)

(array([[-0.7 , -0.47, -0.21],
        [-0.28,  0.44,  0.58],
        [-0.33,  0.29, -0.61],
        [-0.38, -0.37,  0.49],
        [-0.41,  0.61,  0.01]]),
 array([14.71,  3.69,  1.71]),
 array([[-0.6 , -0.65, -0.46],
        [ 0.6 ,  0.02, -0.8 ],
        [ 0.53, -0.76,  0.38]]))